### ISSUE TITLE
Getting api.get_ministering_full() to work? 

### ISSUE THREAD

**Issue by connwork** [mackliet/church_of_jesus_christ_api#11]
I'm not sure if maybe I don't have the permissions for this endpoint, but I think I should. I see all of this info on the website. 

Specifically looking for EQ/RS counselor assigned over ministering comps. 

I get this error: 
`AssertionError: b'{"timestamp":"2024-02-15T03:26:55.370+00:00","status":400,"error":"Bad Request","path":"/services/umlu/v1/ministering/data-full","generalError":true,"message":"Sorry, something went wrong loading the requested data. Try refreshing the page, or try again later."}'`

Any ideas here?

**Comment by mackliet** [comment]
I'm an assistant EQ secretary and it's not working for me either. Most likely the backend has changed something, I'll see if I can fix it real quick

**Comment by mackliet** [comment]
It looks like the backend requires a type query parameter now. I added "type=ALL" to the URL and it worked. I'll push the change now

**Comment by mackliet** [comment]
Published 0.2.8 on pypi, upgrade your package and it should fix your issue

**Comment by connwork** [comment]
Thank you!
