### ISSUE TITLE
Information in api.get_missionary_indicators() and api.get_missionary_progress_record()? 

### ISSUE THREAD

**Issue by connwork** [mackliet/church_of_jesus_christ_api#12]
Hi, 

I'm trying to pull in information from "covenant path" into a ward document. Unfortunately the only api calls I can see that may be related are api.get_missionary_indicators() and api.get_missionary_progress_record(), but both throw errors when attempting to call them. 

`AssertionError: b'{"timestamp":"2024-02-27xxxx","status":404,"error":"Not Found","path":"/services/report/progress-record/xxxxxx/key-indicators","notFound":true,"message":"Sorry, the requested file does not exist."}'`

Any ideas here and if the data I'm after is even possible to wrangle? Very interesting that the church has separated missionary and member data so aggressively.

**Comment by mackliet** [comment]
It looks like the website has changed a bit since I first made this, I'll need to make a new endpoint to get the covenant path data, but it will be pretty simple. I'll find some time this week to look at it.

**Comment by connwork** [comment]
> It looks like the website has changed a bit since I first made this, I'll need to make a new endpoint to get the covenant path data, but it will be pretty simple. I'll find some time this week to look at it.

Thank you! Can you drop a donation link in the Readme? I'm building out something based on this and would love to support you in it.

**Comment by mackliet** [comment]
I know I said this previously, but I'll try to carve out some time to work on it this week. As for a donation link: due to the nature of the project, I feel weird accepting compensation for my time. Don't worry about it haha

**Comment by mackliet** [comment]
I finally got around to doing this while working on some other stuff. It looks like the missionary progress record endpoints have been removed, I added a new get_covenant_path_progress method to get this info
