### ISSUE TITLE
Error in connecting to endpoint.

### ISSUE THREAD

**Issue by connwork** [mackliet/church_of_jesus_christ_api#14]
Again, thank you so much for maintaining this API. Please put a link somewhere so I can donate a few dollars for your time. 

Today I ran into the following error. Is this something that others are seeing as well?

`AssertionError: b'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"\n    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\n<html xml:lang="en" lang="en">\n<head>\n<meta http-equiv="x-availability" content="out of service"/>\n<meta http-equiv="content-type" content="text/html; charset=utf-8" />\n<meta name="monitor" content="Official Web site of The Church of Jesus Christ of Latter-day Saints \xc2\xa9 2019 Intellectual Reserve, Inc.. MonitorApp" />\n<link type="text/css" href="/static/alerts.css" rel="stylesheet" />\n<title>Service Unavailable</title>\n</head>\n<body id="error-page">\n\n<div class="supercenter">\n\t<center>\n\t<h1><font color="#333366">The Service is Currently Unavailable</font></h1>\n\t\n\t<p>We\'re sorry about the inconvenience. Please come back later. </p>\n        <p><a href="javascript:location.reload()">Click here</a> to try again.</p>\n\n\t<div style="border-top: 0px solid #ddd;">\n\t\t<p><img src="/static/logo-English.jpg" height="380" width="285" /></p>\n\t</div>\n\t</center>\n</div>\n<!-- Site Down: App did not respond to the request before closing the connection or no instances are available -->\n</body>\n</html>\n\n'`

obviously hoping it is just temporary as it says but I've had similar messages with apis in the past that were permanent.

**Comment by mackliet** [comment]
I've noticed things like this happen often on Sundays, most likely due to a spike in usage. If it's not better tonight or tomorrow I can look into it it's a problem with the client

**Comment by connwork** [comment]
You were correct! This was a Sunday only thing!
