### ISSUE TITLE
Authentication Failure

### ISSUE THREAD

**Issue by IsaacsLab42** [mackliet/church_of_jesus_christ_api#16]
I'm getting a new failure while authenticating, which I've never seen before. Has the Church changed the way that authentication works?

```bash
 In [4]: lcr = ChurchOfJesusChristAPI(username, password)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[4], line 1
----> 1 lcr = ChurchOfJesusChristAPI(username, password)

File ~/src/church_of_jesus_christ_api/church_of_jesus_christ_api/church_of_jesus_christ_api.py:177, in ChurchOfJesusChristAPI.__init__(self, username, password, proxies, verify_SSL, timeout_sec)
    162 code = parse_qs(urlparse(resp.headers["location"]).query)["code"][0]
    164 token_json = self.__session.post(
    165     _endpoints["oauth2-token"],
    166     timeout=self.__timeout_sec,
   (...)
    174     },
    175 ).json()
--> 177 self.__access_token = token_json["access_token"]
    179 # Some endpoints require this
    180 self.__session.cookies.set_cookie(
    181     requests.cookies.create_cookie(name="owp", value=token_json["id_token"])
    182 )

KeyError: 'access_token'
```

**Comment by IsaacsLab42** [comment]
As a follow up, I dug a little deeper and this is the error response from the website. So it does appear that they changed their authentication:

```python
print(token_json)
{'error': 'invalid_client', 'error_description': 'The client secret supplied for a confidential client is invalid.'}
```

**Comment by bisaac22** [comment]
I am getting the same error.

**Comment by connwork** [comment]
I am also getting this error. 

My understanding is that the current implementation emulates an android connection to the API with a hardcoded client_id and client_secret. It is likely that this just changed, which would require someone with the know how to retrieve the updated values.

**Comment by dyoung418** [comment]
I am also getting this error.  @mackliet do you think this is fixable?

**Comment by mackliet** [comment]
Thanks everyone for reaching out about this error. I've looked it a little bit, but unfortunately I haven't had a ton of time.

The issue, which I think has been mentioned already, is that the API mimics the login for the Android app, but the login for the app has changed and the API is broken. 

The way I got it working in the past is to run the app on a rooted Android device and use a proxy to spy on the login traffic. The rooted part is important because the app uses certificate pinning, so I was able to bypass that with js-frida. I tried doing this with the new login, and I was unsuccessful

The way I'm going to do it now is similar, I'm going to spy on the traffic for a web login using a proxy to try to recreate it. It is a bit more complicated than the app login though, so I was unable to get it working the other day when I tried. I will spend some more time on it was soon as I can.

**Comment by Salvakiya** [comment]
any progress on this one? If anyone has a spiffy router you might be able to use it to spy on packets too?

**Comment by IsaacsLab42** [comment]
# Background 

Hi all. So I'm not the dev of this package, but in whatever free time I have I've been trying to figure out the authentication mechanism. As the Ward Clerk there are a lot of reports that would be useful to generate, that don't exist in LCR. So scripting the reports would be useful.

I've been recording my login sessions through my browser, and then examining that traffic. There are several GET and POST requests that relate to authentication. I've looked a little as some of the JavaScript that does the authentication as well. I'd love to collaborate with others on this and get the authentication figured out. I don't have the ability to root an Android device and record the traffic from the app. I actually think that would be easier than doing this all through a PC web browser. The way the app interacts with the server is probably closer to what a script should do.

In any case, here is what I've done and learned so far. If anyone knows of something I missed, or got wrong, then I'd love to hear about it.

# What I know so far

* The Church uses some scripts from a company called Okta, which provides authentication and authorization services. Their developer docs are at https://developer.okta.com if anyone wants to start down that rabbit hole. There is a lot to digest.
* The Church appears to use a modified form of the OpenID Connect protocol, which sits on top of OAuth2. So if there are any OpenID/OAuth2 experts your help would be appreciated.
* Many of the POST requests and responses follow along the OpenID Connect protocol specifications, but there are a few that I don't (yet) understand. Specifically, when it comes to the authentication token. The server gives a "stateToken" rather than an identity token. It hands out this state token before any authentication takes place. That is odd and doesn't follow the OpenID spec.
* This state token is returned from the Church servers in the form of JSON embedded in JavaScript embedded in HTML. This is a little weird as the OpenID spec shows the response as being JSON. On the Okta website they show JSON as responses, so I suspect the Church made this modification.
* I've started trying to extract this token from JavaScript by using the Python package BeautifulSoup to parse the `<script>` tag from the response. I can do that, but the next problem is extracting the token. It's embedded in the JavaScript as an encoded string. I haven't hit on a good regex so far to be able to reliably extract the token. 
* I starting down the path of using the `stpyv8` Python package to actually execute the JavaScript and grab the token that way. It's possible, but brings in a lot of dependencies and is a pretty heavy handed approach to extracting the token. I'm also not sure if this would work on Windows or Mac. I'm running on Linux.
* The Requests Auth (https://github.com/Colin-b/requests_auth) package looked promising, but due to what appears to be a modified flow this doesn't work.

# Suspected login sequence

Based on what I've seen so far, I believe this is the sequence of steps that we need to take. I've stripped out any personal information, or tokens that might be personal to my account.

## Step 1

Perform a GET on https://www.churchofjesuschrist.org/services/platform/v4/login?return_uri=https%3A%2F%2Fwww.churchofjesuschrist.org%2Fmy-home%3Flang%3Deng

This will return a redirect request to a new URL, which contains the Client ID and the OpenID scopes "openid profile." It's important to allow this redirect to happen as it starts the authentication process. This is also the call that returns a STATE TOKEN which needs to be parsed from the embedded JavaScript. I'm not going to post of copy of the response here, as it is very long. But this part is where I could use the most help.

## Step 2

POST to https://id.churchofjesuschrist.org/idp/idx/introspect

This POST contains a payload, which includes the STATE TOKEN retrieved during step 1.

Post request:

```json
{
    "stateToken": "Really long state token extracted from previous response"
}
```

Response:

Very long JSON that is not shown. I'm not sure if anything in this response is needed for subsequent steps.

## Step 3

POST to https://id.churchofjesuschrist.org/api/v1/internal/device/nonce

This returns a NONCE. I'm not yet sure what the nonce is used for.

Response:

```json
{
	"nonce": "[NONCE]",
	"expiresAt": 1720122941452
}
```

## Step 4

POST to https://id.churchofjesuschrist.org/idp/idx/identify

This is where you POST the username, and the STATE TOKEN. The server responds with a bunch of JSON data. One of the JSON fields is called "stateHandle" which is used in the next step.

Request:

```json
{
    "identifier": "[USERNAME]",
    "stateHandle": "[STATE TOKEN]"
}
```

Response:

Very long JSON. Not shown. This contains a STATE HANDLE which appears to be needed for the next step.

## Step 5
POST to https://id.churchofjesuschrist.org/idp/idx/challenge/answer

This POST contains the password and the STATE HANDLE (not token).

Request:

```json
{
    "credentials": {
        "passcode": "PASSWORD"
    },
    "stateHandle": "STATE HANDLE from previous step"
}
```

Response:

Long JSON object. Unsure if anything in here is useful yet.

## Step 6

GET from https://id.churchofjesuschrist.org/login/token/redirect?stateToken=TOKEN_VALUE

Where the stateToken TOKEN_VALUE appears to be the first part of the STATE HANDLE from step 5. This GET also performs a redirect to a URL that appears to finish off the authentication.

## Comments

I _believe_ the above to be the proper sequence of events. I'm still working through all of the nuances. I also haven't even looked at the cookies or all of the request headers yet. It's very possible that some of the headers contain information necessary for authentication.

The hardest part of the above sequence is pulling out the STATE TOKEN from the HTML/JavaScript/JSON object in the response to step 1 above. I think once I can manage this the rest will go quickly. If anyone is a regex expert, or knows of another easy way to pull this out then please share it. There is a lot of JavaScript the browser downloads, so I'm worried that something in that JavaScript performs some function that isn't accounted for in the above sequence.

# Misc

Some other Python libraries that I want to look into, but have not yet had time:
* https://github.com/CZ-NIC/pyoidc
* https://github.com/necaris/python3-openid
* https://github.com/curityio/example-python-openid-connect-client
* https://github.com/lepture/authlib
* https://github.com/rohe/oictest

Potentially useful documents and websites:
* https://developer.okta.com/
* https://openid.net/specs/openid-connect-core-1_0.html
* https://openid.net/specs/openid-connect-basic-1_0-47.html
* https://backstage.forgerock.com/docs/am/5.5/AM-5.5-Oidc1-Guide.pdf
* https://pragmaticwebsecurity.com/files/talks/introductionoauth.pdf

Maybe useful, but I'm not sure yet if they are relevant:
* https://auth0.com/docs
* https://developer.auth0.com/

**Comment by mackliet** [comment]
I'm taking some time tonight to try to fix it. Hopefully I get something working. Thank you @IsaacsLab42 for helping dig into this

**Comment by connwork** [comment]
Just wanted to mention that I've been working on this via the Android API angle as well by spinning up an android vm, rooting it, and then attempting to use Frida-js.

I'm new to all of this so it's been slow progress, but might be a good route if you don't have a recent rooted device lying around.

**Comment by mackliet** [comment]
Were you able to spy on the traffic with a proxy? I couldn't get it to work with the Android emulator and Frida, and it seemed to be a Frida problem, but I wasn't sure

**Comment by mackliet** [comment]
I successfully got auth working based on the web login: @IsaacsLab42 thanks for your investigation on that, it definitely made things go a lot smoother! Some of the endpoints are broken even with the fixed auth, and I need to investigate further what's going on. I pushed my work to the fix-auth branch for now if anyone is interested in taking a look at it while I fix the endpoints

**Comment by Salvakiya** [comment]
> I successfully got auth working based on the web login: @IsaacsLab42 thanks for your investigation on that, it definitely made things go a lot smoother! Some of the endpoints are broken even with the fixed auth, and I need to investigate further what's going on. I pushed my work to the fix-auth branch for now if anyone is interested in taking a look at it while I fix the endpoints

looks like there is an added dependency of Json5 that is not defined in the setup.py file on that branch. but its also not currently being used?

**Comment by IsaacsLab42** [comment]
@mackliet Thanks for implementing that! I can help take a look at the endpoints problem when I get home from work this evening.

**Comment by mackliet** [comment]
I fixed various endpoints, removed unused imports, and pushed to my branch. The last few endpoints are a little trickier: the endpoint used by the browser returns HTML rather than JSON, so I'm unsure what the best way to fix it is.

**Comment by IsaacsLab42** [comment]
If you add the header `Accept: application/json` to the request, will it return json back to you?

**Comment by mackliet** [comment]
I was able to get most of the endpoints to work I ended up removing the following methods for now defunct endpoints:
get_mobile_sync_data
get_missionary_indicators
get_missionary_progress_record
get_new_members

I also added the following method:
get_covenant_path_progress

If I can ever get the mobile login flow to work again, I will do that, the web login is much slower than the app login was unfortunately since it needs to login to www.churchofjesuschrist.org, lcr.churchofjesuschrist.org, and directory.churchofjesuschrist.org.

package 0.3.0 is live on pypi, let me know if you have any issues!
