### ISSUE TITLE
Authentication isn't working (for me)

### ISSUE THREAD

**Issue by AFreindlyMissionary** [mackliet/church_of_jesus_christ_api#17]
Hello. In the recent update to authentication, I haven't been able to access any information through the API because of authentication problems.
I'm running a request for my own user's information, but the following error information follows me regardless of what I do. 

`AssertionError: b'{"error":"Forbidden","message":"Access is denied","timestamp":"2024-07-09T15:40:25.050+00:00","status":403}'`

This tells me that it's certainly pinging the right servers to log in, but the servers are denying the request when I make it.
What could be causing this?

**Comment by mackliet** [comment]
I found a different endpoint that the website uses to get details on the user's unit and began using it, but it looks like the endpoint I chose requires some permissions that you don't have. I switched to using one from directory.churchofjesuschrist.org. This should fix your issue, go ahead and download version 0.3.1 and it should work. If it doesn't, go ahead and reopen the issue.
