### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by dan3093** [mackliet/church_of_jesus_christ_api#20]
Like others, I am also getting the following error:

"AssertionError: b'{"error":"Forbidden","message":"Access is denied","timestamp":"2024-08-07T02:11:34.247+00:00","status":403}'"

I do not have access to the LCR with my current calling, but I am trying to find a quick way to export all members, emails, mobile phone numbers that are available in the ward directory so I can send out an email/text when it is our wards week to clean the ward house.

The previous ward cleaning specialist had created groups of less than 15 in the tools app and manually sent out group messages to the smaller groups - I would like to avoid going that route.

Does this module require the user to have permissions to the LCR tools to access the information I am looking to pull?

**Comment by mackliet** [comment]
I think as of right now I'm making the assumption that the user has LCR
access. I'll try to find some time to fix that tomorrow

**Comment by mackliet** [comment]
Pushed a new revision, API construction will work now even if you don't have LCR access. Tested using an account without LCR access with the get_directory endpoint

**Comment by dan3093** [comment]
I really appreciate it! Thanks
