### ISSUE TITLE
`login_oauth_token` URL no longer works

### ISSUE THREAD

**Issue by shampto3** [mackliet/church_of_jesus_christ_api#4]
Thank you for creating this package, it was exactly what I needed. Unfortunately it seems that the church has updated how they handle authentication, so getting a session token no longer works. The `login_oauth_token` URL used is returning a 400 response. You might already be aware of this, but I thought I'd create this issue just in case.

I briefly attempted to see if I could figure out what the new URL was to see if it was a simple string update, but I couldn't get it to work. I might try again soon. If I get a fix working, I'll be sure to submit a PR.

**Comment by elmerohueso** [comment]
I can confirm the issue. It was working last week. The full response is {"error_description":"Client authentication failed","error":"invalid_client"}.

**Comment by bisaac22** [comment]
To echo above. I love this package. Thank you so very much. It has been a huge help to us. Also confirming the above error. We are having the same issue starting a few days ago.

**Comment by mackliet** [comment]
I will try to find time to work on this issue during the week: I'm glad to see that the package is getting a lot of use!

**Comment by mackliet** [comment]
Quick update, I've spent some time on fixing this issue this week, and I'm really close to putting up a fix. I think I can have something up today or tomorrow

**Comment by mackliet** [comment]
Done. 0.2.0 is published with bugfixes. I also just removed the get_mobile_sync, download_patriarchal_blessing, and get_donation_history endpoints because they were either completely broken now or often failed. A nice side effect of updating the auth is that directory.churchofjesuschrist.org endpoints can now also be used. I switched get_directory to go through there instead of the mobile app endpoints, and I added a get_units method which is all I know that people were using get_mobile_sync for anyway.

**Comment by bisaac22** [comment]
Thanks! It is working again.

**Comment by shampto3** [comment]
Thanks! It's working great. 🎉

**Comment by elmerohueso** [comment]
> mobile_sync

@mackliet Does the mobile_sync endpoint not work with the new authentication? That endpoint returned things like mrn, mother, and father for all members, which made associating parents simple. The other endpoints only return those properties for my old household (even though, according to my viewing rights in Tools and the web as Executive Secretary, I'd think it would return them for all members).

**Comment by mackliet** [comment]
> > mobile_sync
> 
> @mackliet Does the mobile_sync endpoint not work with the new authentication? That endpoint returned things like mrn, mother, and father for all members, which made associating parents simple. The other endpoints only return those properties for my old household (even though, according to my viewing rights in Tools and the web as Executive Secretary, I'd think it would return them for all members).

It "worked", but when I was testing against it the other day it would frequently return 5xx errors, and the time it took to respond was also much worse other endpoints. I didn't think anyone was using it for anything since I had only recently added it, but I can go ahead and add it back in

**Comment by mackliet** [comment]
@elmerohueso go ahead and update to 0.2.2, I added get_mobile_sync_data back in

**Comment by elmerohueso** [comment]
@mackliet Thanks!
