### ISSUE TITLE
not_authenticated

### ISSUE THREAD

**Issue by bisaac22** [mackliet/church_of_jesus_christ_api#5]
I may have something messed up on my end, but starting this morning I am getting an authentication error.

When I call:
       lds = ChurchOfJesusChristAPI(username,password)
I am getting:
       AssertionError: b'{"error":"not_authenticated","description":"The user does not have an active session or is not authenticated"}'

Did something change?

**Comment by mackliet** [comment]
It looks like I'm having the same problem now as well. I'll see if it's a quick fix

**Comment by mackliet** [comment]
Something changed with the auth at directory.churchofjesuschrist.org. I switched it to use membertools-api.churchofjesuschrist.org and it seems to work now. There are slight changes in the return values from affected endpoints (get_directory, get_units, user_details), but everything else seems to be working fine.
