### ISSUE TITLE
Take "timeout" input parameter

### ISSUE THREAD

**Issue by elmerohueso** [mackliet/church_of_jesus_christ_api#6]
I've been having to increase the session timeouts lately from the 15 seconds in the script. It might be nice to add a"timeout" parameter with a 15 second default but allowing for a user-specified timeout.

**Comment by mackliet** [comment]
I added a timeout_sec parameter to all the get methods and a timeout_sec parameter to the constructor to set a default, similar to your previous pull request. I think this should solve your issue, if you find any issues, let me know
